# Generated by Django 3.1b1 on 2020-08-25 08:16

import article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200818_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(default='SOME STRING', upload_to=article.models.get_upload_file_name),
        ),
    ]
