# Generated by Django 3.1b1 on 2020-08-27 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_auto_20200827_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='likes',
            field=models.IntegerField(null=True),
        ),
    ]
