# Generated by Django 3.1.1 on 2020-10-02 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='likes_cheese',
            field=models.BooleanField(default=False),
        ),
    ]
